name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
        cache: gradle
    - name: Build the JAR
      run: ./gradlew shadowJar
    - name: Build the Docker image
      run: docker build -t ghcr.io/goyozi/happy .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Push the Docker image
      run: docker push ghcr.io/goyozi/happy
